# Project Information
site_name: VMware.CloudFoundation.PasswordManagement
site_description: PowerShell Module for VMware Cloud Foundation Password Management
site_url: https://vmware.github.io/powershell-module-for-vmware-cloud-foundation-password-management
site_author: Broadcom
docs_dir: docs
site_dir: .site
use_directory_urls: true

# Repository
repo_url: https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management
edit_uri: blob/main/docs/

# Copyright
copyright: |
  Copyright &copy; 2005-2024 Broadcom. All Rights Reserved.<br/>
  The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.<br/><br/>

# Configuration
theme:
  name: material
  favicon: favicon.ico
  logo: assets/images/icon-white.svg
  icon:
    repo: fontawesome/brands/github
  palette:  
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Dark Theme
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Light Theme
  font:
    text: Roboto
    code: Roboto Mono
  features:
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - navigation.footer
  - navigation.header
  - navigation.indexes
  - navigation.instant
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

# Plugins
plugins:
- search:
    separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
- open-in-new-tab
- markdownextradata:
    jinja_options:
      variable_start_string: "${{"
      variable_end_string: "}}"
- git-authors
- git-revision-date-localized:
    enabled: !ENV [CI, false]
    enable_creation_date: false
    exclude:
      - index.md
    fallback_to_build_date: true
    type: timeago

# Customization
extra:
  config:
    repo_url: https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management
    repo_url_raw: https://raw.githubusercontent.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management
  version:
    default: latest
    provider: mike
extra_css:
  - assets/stylesheets/extra.css

# Extensions
markdown_extensions:
- admonition
- attr_list
- footnotes
- md_in_html
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
    options:
      custom_icons:
      - material/.icons
- pymdownx.inlinehilite
- pymdownx.highlight:
    use_pygments: true
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.details
- tables
- toc:
    permalink: true

# Navigation
nav:
- Getting Started: 
  - index.md
  - Installation: install.md
  - Updating: update.md
  - User Access: user-access.md
  - Release Notes: release-notes.md
  - Release Milestones: https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/milestones
  - License: license.md
- Reference:
  - documentation/index.md
  - Functions:
    - General:
      - Get-PasswordPolicyDefault: documentation/functions/Get-PasswordPolicyDefault.md
      - Invoke-PasswordPolicyManager: documentation/functions/Invoke-PasswordPolicyManager.md
      - Invoke-PasswordRotationManager: documentation/functions/Invoke-PasswordRotationManager.md
      - Request-LocalUserPasswordExpiration: documentation/functions/Request-LocalUserPasswordExpiration.md
      - Start-PasswordPolicyConfig: documentation/functions/Start-PasswordPolicyConfig.md
      - Test-VcfPasswordManagementPrereq: documentation/functions/Test-VcfPasswordManagementPrereq.md
      - Update-LocalUserPasswordExpiration: documentation/functions/Update-LocalUserPasswordExpiration.md
    - Account Lockout:
      - SDDC Manager:
        - Publish-SddcManagerAccountLockout: documentation/functions/Publish-SddcManagerAccountLockout.md
        - Request-SddcManagerAccountLockout: documentation/functions/Request-SddcManagerAccountLockout.md
        - Update-SddcManagerAccountLockout: documentation/functions/Update-SddcManagerAccountLockout.md
      - vCenter Single Sign-On:
        - Publish-SsoPasswordPolicy: documentation/functions/Publish-SsoPasswordPolicy.md
        - Request-SsoAccountLockout: documentation/functions/Request-SsoAccountLockout.md
        - Update-SsoAccountLockout: documentation/functions/Update-SsoAccountLockout.md
      - vCenter Server:
        - Publish-VcenterLocalAccountLockout: documentation/functions/Publish-VcenterLocalAccountLockout.md
        - Request-VcenterAccountLockout: documentation/functions/Request-VcenterAccountLockout.md
        - Update-VcenterAccountLockout: documentation/functions/Update-VcenterAccountLockout.md
      - NSX Manager:
        - Publish-NsxManagerAccountLockout: documentation/functions/Publish-NsxManagerAccountLockout.md        
        - Request-NsxtManagerAccountLockout: documentation/functions/Request-NsxtManagerAccountLockout.md
        - Update-NsxtManagerAccountLockout: documentation/functions/Update-NsxtManagerAccountLockout.md
      - NSX Edge:
        - Publish-NsxEdgeAccountLockout: documentation/functions/Publish-NsxEdgeAccountLockout.md
        - Request-NsxtEdgeAccountLockout: documentation/functions/Request-NsxtEdgeAccountLockout.md
        - Update-NsxtEdgeAccountLockout: documentation/functions/Update-NsxtEdgeAccountLockout.md
      - ESXi:
        - Publish-EsxiPasswordPolicy: documentation/functions/Publish-EsxiPasswordPolicy.md
        - Request-EsxiAccountLockout: documentation/functions/Request-EsxiAccountLockout.md
        - Update-EsxiAccountLockout: documentation/functions/Update-EsxiAccountLockout.md
      - Workspace ONE Access:
        - Publish-WsaDirectoryPasswordPolicy: documentation/functions/Publish-WsaDirectoryPasswordPolicy.md
        - Publish-WsaLocalPasswordPolicy: documentation/functions/Publish-WsaLocalPasswordPolicy.md
        - Request-WsaAccountLockout: documentation/functions/Request-WsaAccountLockout.md
        - Request-WsaLocalUserAccountLockout: documentation/functions/Request-WsaLocalUserAccountLockout.md
        - Update-WsaAccountLockout: documentation/functions/Update-WsaAccountLockout.md
        - Update-WsaLocalUserAccountLockout: documentation/functions/Update-WsaLocalUserAccountLockout.md
    - Password Expiration:
      - SDDC Manager:
        - Publish-SddcManagerPasswordExpiration: documentation/functions/Publish-SddcManagerPasswordExpiration.md
        - Request-SddcManagerPasswordExpiration: documentation/functions/Request-SddcManagerPasswordExpiration.md
        - Update-SddcManagerPasswordExpiration: documentation/functions/Update-SddcManagerPasswordExpiration.md
      - vCenter Server:
        - Publish-VcenterLocalPasswordExpiration: documentation/functions/Publish-VcenterLocalPasswordExpiration.md
        - Publish-VcenterPasswordExpiration: documentation/functions/Publish-VcenterPasswordExpiration.md
        - Request-VcenterPasswordExpiration: documentation/functions/Request-VcenterPasswordExpiration.md
        - Request-VcenterRootPasswordExpiration: documentation/functions/Request-VcenterRootPasswordExpiration.md
        - Update-VcenterPasswordExpiration: documentation/functions/Update-VcenterPasswordExpiration.md
        - Update-VcenterRootPasswordExpiration: documentation/functions/Update-VcenterRootPasswordExpiration.md
      - vCenter Single Sign-On:
        - Publish-SsoPasswordPolicy: documentation/functions/Publish-SsoPasswordPolicy.md
        - Request-SsoPasswordExpiration: documentation/functions/Request-SsoPasswordExpiration.md
        - Update-SsoPasswordExpiration: documentation/functions/Update-SsoPasswordExpiration.md
      - NSX Manager:
        - Publish-NsxManagerPasswordExpiration: documentation/functions/Publish-NsxManagerPasswordExpiration.md
        - Request-NsxtManagerPasswordExpiration: documentation/functions/Request-NsxtManagerPasswordExpiration.md
        - Update-NsxtManagerPasswordExpiration: documentation/functions/Update-NsxtManagerPasswordExpiration.md
      - NSX Edge:
        - Publish-NsxEdgePasswordExpiration: documentation/functions/Publish-NsxEdgePasswordExpiration.md
        - Request-NsxtEdgePasswordExpiration: documentation/functions/Request-NsxtEdgePasswordExpiration.md
        - Update-NsxtEdgePasswordExpiration: documentation/functions/Update-NsxtEdgePasswordExpiration.md 
      - ESXi:
        - Publish-EsxiPasswordPolicy: documentation/functions/Publish-EsxiPasswordPolicy.md
        - Request-EsxiPasswordExpiration: documentation/functions/Request-EsxiPasswordExpiration.md
        - Update-EsxiPasswordExpiration: documentation/functions/Update-EsxiPasswordExpiration.md
      - Workspace ONE Access:
        - Publish-WsaDirectoryPasswordPolicy: documentation/functions/Publish-WsaDirectoryPasswordPolicy.md
        - Publish-WsaLocalPasswordPolicy: documentation/functions/Publish-WsaLocalPasswordPolicy.md
        - Request-WsaPasswordExpiration: documentation/functions/Request-WsaPasswordExpiration.md
        - Update-WsaPasswordExpiration: documentation/functions/Update-WsaPasswordExpiration.md
    - Password Complexity:
      - SDDC Manager:
        - Publish-SddcManagerPasswordComplexity: documentation/functions/Publish-SddcManagerPasswordComplexity.md
        - Request-SddcManagerPasswordComplexity: documentation/functions/Request-SddcManagerPasswordComplexity.md
        - Update-SddcManagerPasswordComplexity: documentation/functions/Update-SddcManagerPasswordComplexity.md
      - vCenter Server:
        - Publish-VcenterLocalPasswordComplexity: documentation/functions/Publish-VcenterLocalPasswordComplexity.md
        - Request-VcenterPasswordComplexity: documentation/functions/Request-VcenterPasswordComplexity.md
        - Update-VcenterPasswordComplexity: documentation/functions/Update-VcenterPasswordComplexity.md
      - vCenter Single Sign-On:
        - Publish-SsoPasswordPolicy: documentation/functions/Publish-SsoPasswordPolicy.md
        - Request-SsoPasswordComplexity: documentation/functions/Request-SsoPasswordComplexity.md
        - Update-SsoPasswordComplexity: documentation/functions/Update-SsoPasswordComplexity.md
      - NSX Manager:
        - Publish-NsxManagerPasswordComplexity: documentation/functions/Publish-NsxManagerPasswordComplexity.md
        - Request-NsxtManagerPasswordComplexity: documentation/functions/Request-NsxtManagerPasswordComplexity.md
        - Update-NsxtManagerPasswordComplexity: documentation/functions/Update-NsxtManagerPasswordComplexity.md
      - NSX Edge:
        - Publish-NsxEdgePasswordComplexity: documentation/functions/Publish-NsxEdgePasswordComplexity.md
        - Request-NsxtEdgePasswordComplexity: documentation/functions/Request-NsxtEdgePasswordComplexity.md
        - Update-NsxtEdgePasswordComplexity: documentation/functions/Update-NsxtEdgePasswordComplexity.md
      - ESXi:
        - Publish-EsxiPasswordPolicy: documentation/functions/Publish-EsxiPasswordPolicy.md
        - Request-EsxiPasswordComplexity: documentation/functions/Request-EsxiPasswordComplexity.md
        - Update-EsxiPasswordComplexity: documentation/functions/Update-EsxiPasswordComplexity.md
      - Workspace ONE Access:
        - Publish-WsaDirectoryPasswordPolicy: documentation/functions/Publish-WsaDirectoryPasswordPolicy.md
        - Publish-WsaLocalPasswordPolicy: documentation/functions/Publish-WsaLocalPasswordPolicy.md
        - Request-WsaPasswordComplexity: documentation/functions/Request-WsaPasswordComplexity.md
        - Request-WsaLocalUserPasswordComplexity: documentation/functions/Request-WsaLocalUserPasswordComplexity.md
        - Update-WsaPasswordComplexity: documentation/functions/Update-WsaPasswordComplexity.md
        - Update-WsaLocalUserPasswordComplexity: documentation/functions/Update-WsaLocalUserPasswordComplexity.md
    - Password Rotation:
      - Publish-PasswordRotationPolicy: documentation/functions/Publish-PasswordRotationPolicy.md
      - Request-PasswordRotationPolicy: documentation/functions/Request-PasswordRotationPolicy.md
      - Update-PasswordRotationPolicy: documentation/functions/Update-PasswordRotationPolicy.md
- Community:
  - community/index.md
  - Contributing: community/contributing.md
  - Discussions: https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/discussions
  - Search Issues: https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/issues
  - Open an Issue: https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/issues/new/choose
  - Support: community/support.md
  - Code of Conduct: community/code-of-conduct.md
