blank_issues_enabled: false
contact_links:
  - name: Module Documentation
    url: 'https://vmware.github.io/powershell-module-for-vmware-cloud-foundation-password-management'
    about: Having trouble with the module? Check out the documentation.
  - name: VMware Cloud Foundation Product Documentation
    url: https://docs.vmware.com/en/VMware-Cloud-Foundation/
    about: Efficiently manage virtual machine and container workloads. Deliver cloud benefits to on-premises, full-stack hyperconverged infrastructure deployments.
